language: ruby
rvm:
  - 2.5

before_install:
  - yes | gem update --system --force --no-document
  - gem install bundler --no-document

script: "bundle exec jekyll build"

branches:
  only:
    - master
