# Site settings
title: jekyll-basic-theme test pages
description: "This is a skeleton theme. It is meant to be used as a basis for other themes."
meta-description: "Calin Radoni's jekyll-basic-theme for GitHub Pages"
meta-keywords: "Jekyll, Jekyll theme, GutHub Pages, Calin Radoni"

author:
  name: Calin Radoni
  email: CalinRadoni@users.noreply.github.com
  copyright-text: 2020
url: "https://github.com/CalinRadoni/jekyll-basic-theme"
github_username: CalinRadoni

# set the date format to ISO8601. See https://shopify.github.io/liquid/filters/date/ for other formats
date-format: "%F"

skin: light

# Build settings
markdown: kramdown

# Exclusions ...
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# ... and inclusions
include:
  - _pages

# Change default permalink format
permalink: /pages/:short_year:month:day-:slug:output_ext
