# ------------------------------------------------------------------------------
# Site settings
# ------------------------------------------------------------------------------

title: "jekyll-basic-theme"
tagline: "jekyll-basic-theme skeleton theme"
description: "This is a skeleton theme. It is meant to be used as a basis for other themes."
# logo: /assets/img/logo.png

# the base hostname and protocol of the site
url: "https://calinradoni.github.io/"

# ------------------------------------------------------------------------------
# Theme settings
# ------------------------------------------------------------------------------

author-name: "Calin Radoni"
author-email: CalinRadoni@users.noreply.github.com
copyright-text: "2020"

# set the date format to ISO8601. See https://shopify.github.io/liquid/filters/date/ for other formats
date-format: "%F"

skin: light

social-links:
  - site: GitHub
    link: https://github.com/CalinRadoni
  - site: LinkedIn
    link: https://www.linkedin.com/in/...

# ------------------------------------------------------------------------------
# Jekyll settings
# ------------------------------------------------------------------------------

markdown: kramdown

# change the permalink format
permalink: /pages/:short_year:month:day-:slug:output_ext

# exclusions ...
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# ... and inclusions
include:
  - _pages

# required plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
